name: cred_manager
description: Flutter frontend for API Key Manager authentication system.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  cryptography: ^2.7.0
  jwt_decode: ^0.3.1
  sqflite_sqlcipher: ^3.3.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  hex: ^0.2.0
  path: ^1.8.3
  convert: ^3.1.1
  path_provider: ^2.1.1
  local_auth: ^2.1.6
  window_manager: ^0.3.9
  pdf: ^3.10.7
  printing: ^5.11.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  fastforge: ^0.6.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/